### ISSUE TITLE
[Feature request] Display layout in use

### ISSUE THREAD

**Issue by stefonarch** [AlexJakeGreen/wayfire-kbdd-plugin#10]
As it doesn't seem possible to get the  layout in wayfire would it be possible that this plugin writes the actual keyboard layout (reading and counting off wayfire.ini maybe) to some place|file which would allow creating an keyboard indicator (reading from it)?

**Comment by AlexJakeGreen** [comment]
Good question. I thought about a plugin which constantly (example: every 1 second) polls which layout is active now. This does not look like a good solution and it can drain laptop batteries faster.

Unfortunately, this plugin does not intercept the switch of layout. It is only triggered when some window gets activated.
I think we need somehow intercept the layout switch key combination, and, it looks like it needs some modifications in wayfire code.

**Comment by stefonarch** [comment]
I'm using a similar workaround atm, in wayfire.ini
`xkb_options = grp:alt_shift_toggle,grp_led:scroll`
and lxqt-panel has a "custom command" plugin which displays:

```
if [ "$(cat /sys/class/leds/input3\:\:scrolllock/brightness)" == "1" ]; then echo ' CH';else echo ' IT'; fi

```

it runs every second, I think the power consumption is minimal but sure it's not perfect and it only works for 2 layout and if you're not using scrolllock. 

T

**Comment by stefonarch** [comment]
Thinking about it: this plugin knows the layout (default or previuos for each window right? So couldn't it calculate/count it from wayfire.ini's  `xkb_layout = x,y,z` ?

**Comment by AlexJakeGreen** [comment]
We need API stabilization https://github.com/WayfireWM/wayfire/issues/1317
We're not masochists to rewrite everything each time API was changed.

**Comment by AlexJakeGreen** [comment]
I did some research in a separate repo https://github.com/AlexJakeGreen/wayfire-kbd-layout-plugin/blob/master/src/kbd-layout.cpp
It exposes the current layout via a file:
```
$ cat /tmp/layout.json 
{"layout_id": 2, "layout_name": "English (US)"}
```

**Comment by AlexJakeGreen** [comment]
Done. Now layout is exported to a file.
```
$ cat /tmp/layout.json 
{"id": 0, "name": "Polish", "code": "pl"}
```

**Comment by stefonarch** [comment]
Nice! Am I right that it compiles only with wayfire git master? Trying with 0.8 I get
```
-c ../src/kbdd.cpp
In file included from ../src/kbdd.cpp:4:
/usr/include/wayfire/nonstd/wlroots-full.hpp:35:10: fatal error: wlr/types/wlr_output_damage.h: No such file or directory
   35 | #include <wlr/types/wlr_output_damage.h>

```

**Comment by AlexJakeGreen** [comment]
Hi @stefonarch 
I compiled from this tarball https://github.com/WayfireWM/wayfire/releases/tag/v0.8.0
Which version you usually use, git master?

**Comment by stefonarch** [comment]
I compiled master wayfire now and the issue is gone. labwc 0.7.x runs on wlroots 0.17 indeed and the `.json` file it present in `/tmp`
Anyway until the lxqt-desktop-shell plugin does'nt work again wayfire is unusable to me.
